name: CI - Website

on:
  workflow_call:
  pull_request:
    paths:
      - website/**
      - .github/workflows/ci-website.yml

defaults:
  run:
    working-directory: ./website

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        # Installs dependencies directly from package.lock
        # and skips dependency resolution etc.
        run: npm ci

      - name: Lint and format
        run: |
          npm run check:lint
          npm run check:format

      - name: Check spelling
        run: npm run check:spelling

      - name: Check astro files
        run: npm run check:astro

      - name: Build site
        run: npm run build

      - name: Audit dependencies
        run: npm audit
